# Generated by Django 4.1.5 on 2023-01-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0002_alter_band_spo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BandFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ocena", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
