# Generated by Django 4.1.5 on 2023-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0003_bandfinal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BandFinal",
        ),
        migrations.AddField(
            model_name="band",
            name="dex_ocena",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="band",
            name="name",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
