# Generated by Django 4.1.5 on 2023-01-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0004_delete_bandfinal_band_dex_ocena_band_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="dex_ocena",
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
        ),
    ]
