# Generated by Django 4.1.5 on 2023-01-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0005_alter_band_dex_ocena"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="author_songs",
            field=models.CharField(
                choices=[
                    ("less than 3", "Izvajalec ima manj kot 3 avtorske pesmi"),
                    ("less than 10", "Izvajalec ima več kot 10 avtorskih pesmi"),
                    ("more than 10", "Izvajalec ima več kot 10 avtorskih pesmi"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="fb",
            field=models.CharField(
                choices=[
                    (
                        "less than 1000",
                        "Izvajalec ima manj kot 1000 sledilcev na Facebooku.",
                    ),
                    (
                        "less than 1500",
                        "Izvajalec ima manj kot 1500 sledilcev na Facebooku.",
                    ),
                    (
                        "more than 2000",
                        "Izvajalec ima več kot 2000 sledilcev na Facebooku.",
                    ),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="hits",
            field=models.CharField(
                choices=[
                    (
                        "0",
                        "Izvajalec nima nobenega hita (skladbe z več kot 50.000 poslušanji na YT.",
                    ),
                    ("1-4", "Izvajalec ima 1 do 4 hitov."),
                    ("5 or more", "Izvajalec ima 5 ali več hitov"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="ig",
            field=models.CharField(
                choices=[
                    (
                        "less than 1.500",
                        "Izvajalec ima manj kot 1500 sledilcev na Instagramu.",
                    ),
                    (
                        "less than 3.000",
                        "Izvajalec ima manj kot 3000 sledilcev na Instagramu.",
                    ),
                    (
                        "more than 5.000",
                        "Izvajalec ima več kot 3000 sledilcev na Instagramu.",
                    ),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="last_concert",
            field=models.CharField(
                choices=[
                    (
                        "1 year ago",
                        "Izvajalec je imel v Novem mestu koncert manj kot eno leto nazaj.",
                    ),
                    (
                        "2 years ago",
                        "Izvajalec je imel v Novem mestu koncert manj kot dve leti nazaj.",
                    ),
                    ("Never", "Izvajalec v Novem mestu še ni nastopal. "),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="price",
            field=models.CharField(
                choices=[
                    ("more than 2000", "Več kot 2000 evrov"),
                    ("less than 2000", "Manj kot 2000 evrov"),
                    ("less than 1500", "Manj kot 1500 evrov"),
                    ("less than 1000", "Manj kot 1000 evrov"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="spo",
            field=models.CharField(
                choices=[
                    ("less than 1000", "Manj kot 1000 mesečnih poslušalcev"),
                    ("less than 2000", "Manj kot 2000 mesečnih poslušalcev"),
                    ("less than 3500", "Manj kot 3500 mesečnih poslušalcev"),
                    ("more than 3500", "Več kot 3500 mesečnih poslušalcev"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="yt",
            field=models.CharField(
                choices=[
                    ("less than 50.000", "Manj kot 50.000 ogledov"),
                    ("less than 150.000", "Manj kot 150.000 ogledov"),
                    ("less than 300.000", "Manj kot 300.000 ogledov"),
                    ("more than 300.000", "Več kot 300.000 ogledov"),
                ],
                max_length=100,
            ),
        ),
    ]
