# Generated by Django 4.1.5 on 2023-01-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0007_alter_band_ig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Band",
        ),
    ]
