# Generated by Django 4.1.5 on 2023-01-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0009_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="name",
        ),
    ]
