# Generated by Django 4.1.5 on 2023-01-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0010_remove_band_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="attributes",
        ),
        migrations.AddField(
            model_name="band",
            name="attribute",
            field=models.CharField(default="default value", max_length=255),
        ),
        migrations.AddField(
            model_name="band",
            name="name",
            field=models.CharField(default="No Name", max_length=255),
        ),
        migrations.AddField(
            model_name="band",
            name="ocena",
            field=models.IntegerField(default=0),
        ),
    ]
