# Generated by Django 4.1.5 on 2023-01-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0012_alter_band_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Band",
        ),
    ]
