# Generated by Django 4.1.5 on 2023-01-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0014_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandresults",
            name="dex_ocena",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="bandresults",
            name="name",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
