# Generated by Django 4.1.5 on 2023-01-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandmodels", "0017_alter_bandresults_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandresults",
            name="name",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
